-- Migration: Add Universities and Colleges Tables
-- Purpose: Store university and college data for cascading dropdowns

CREATE TABLE IF NOT EXISTS universities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    state_id INT,
    state_name VARCHAR(100),
    country_id INT DEFAULT 105,
    university_type VARCHAR(50) COMMENT 'State, Private, Central, Deemed to be Universities',
    established_year INT,
    website VARCHAR(255),
    email VARCHAR(100),
    phone VARCHAR(20),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (state_id) REFERENCES states(id) ON DELETE SET NULL,
    FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE SET NULL,
    INDEX idx_state_id (state_id),
    INDEX idx_country_id (country_id),
    INDEX idx_name (name),
    INDEX idx_university_type (university_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS colleges (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    university_id INT,
    university_name VARCHAR(255),
    city_id INT,
    city_name VARCHAR(100),
    state_id INT,
    state_name VARCHAR(100),
    country_id INT DEFAULT 105,
    college_type VARCHAR(50) COMMENT 'Government, Private, Aided, Unaided',
    established_year INT,
    affiliation_number VARCHAR(100),
    website VARCHAR(255),
    email VARCHAR(100),
    phone VARCHAR(20),
    address TEXT,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    accreditation_status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (university_id) REFERENCES universities(id) ON DELETE CASCADE,
    FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE SET NULL,
    FOREIGN KEY (state_id) REFERENCES states(id) ON DELETE SET NULL,
    FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE SET NULL,
    INDEX idx_university_id (university_id),
    INDEX idx_city_id (city_id),
    INDEX idx_state_id (state_id),
    INDEX idx_country_id (country_id),
    INDEX idx_name (name),
    INDEX idx_college_type (college_type),
    UNIQUE KEY unique_college_university (name, university_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
